<?php

function caesar_cipher_menu() {
    $items = array();
        $items['caesar_cipher'] = array(
        'title' => 'Encrypt Your Text!',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('caesar_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['done'] = array(
        'title' => 'Done!',
        'page callback' => 'caesar_cipher_done',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function caesar_cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => 'Number of Spaces you wish to shift each letter over',
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );

    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => 'Left or Right Shift',
        '#element_validate' => array('element_validate_specific_text'),
        '#required' => TRUE,
    );

    $form['user_input'] = array(
        '#title' => 'Text to be Encrypted',
        '#type' => 'textfield',
        '#description' => 'Enter the Word(s) you would like to scramble',
        '#element_validate' => array('element_validate_required_characters'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt',
    );

    return $form;
}

function element_validate_specific_text($element) {
    if($element['#value'] != ('right' || 'left')) {
        form_error($element, t('Please enter Left or Right'));
    }
}

function element_validate_required_characters($element) {
    $input = str_split($element['#value']);
    if(in_array(array(' ', '/', ':', ';', '*', '&', '$', '#', '@', '!'), $input)) {
        form_error($element, t('Please ReEnter without special characters'));
    }
}

function caesar_cipher_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    $shift_direction = $form_state['values']['shift_direction'];
    $input = $form_state['values']['user_input'];
    $alphabet = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'];
    $reverse_alphabet = array_flip($alphabet);
    $output = " ";
    $shift_direction = strtolower($shift_direction);
    $input = strtolower($input);
    $split_input = str_split($input);

    if($shift_direction == 'left'){
        for($i=0; $i<strlen($input); $i++) {
            $output.= $alphabet[($reverse_alphabet[$split_input[$i]] - $shift_value) % 26];
        }
    } else if($shift_direction == 'right') {
        for($i=0; $i<strlen($input); $i++) {
            $output.= $alphabet[($reverse_alphabet[$split_input[$i]] + $shift_value) % 26];
        }
    } else {
        $output = "There Was an Error";
    }

    $_SESSION['final_output'] = $output;
    $form_state['redirect'] = 'done';
}

function caesar_cipher_done() {
    "<p>this works</p>";
    return $_SESSION['final_output'];
}
