<?php

function caesar_cipher_menu() {
    $items = array();
        $items['caesar_cipher'] = array(
        'title' => 'Encrypt Your Text!',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('caesar_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['done'] = array(
        'title' => 'Done!',
        'page callback' => 'caesar_cipher_done',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function caesar_cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift Value',
        '#type' => 'textfield',
        '#description' => 'Number of Spaces you wish to shift each letter over',
        '#required' => TRUE,
    );

    $form['shift_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => 'Left or Right Shift',
        '#required' => TRUE,
    );

    $form['user_input'] = array(
        '#title' => 'Text to be Encrypted',
        '#type' => 'textfield',
        '#description' => 'Enter the Word(s) you would like to scramble',
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt',
    );

    return $form;
}

function caesar_cipher_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    $shift_direction = $form_state['values']['shift_direction'];
    $input = $form_state['values']['user_input'];

    $alphabet_one = ['a' => 'b','b' => 'c','c' => 'd','d' => 'e','e' => 'f','f' => 'g','g' => 'h','h' => 'i','i' => 'i','j' => 'k','k' => 'l','l' => 'm','m' => 'n','n' => 'o','o' => 'p','p' => 'q','q' =>'r','r' => 's','s' => 't','t' => 'u','u' => 'v','v' => 'w','w' => 'x','x' => 'y','y' => 'z','z' => 'a'];
    $alphabet_two = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'];
    $alphabet_three = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'];
    $output = " ";

    $input = strtolower($input);
    $exploded_input = explode(" ", $input);
    $length = strlen($exploded_input);

    if($shift_value == 1) {
        for($i = 0;$i<$length; $i++) {
            if(in_array($exploded_input[$i], $alphabet_one[$i]) {
                array_push($output, $exploded_input);
        }
    }
}
    $imploded_output = implode($output);
    $final_output = ucfirst($imploded_output);
    $_SESSION['final_output'] = $final_output;
    $form_state['redirect'] = 'done';
}

function caesar_cipher_done() {
    return $_SESSION['final_output'];
}
